# Generated by Django 5.1.2 on 2024-11-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado_vehiculo',
            field=models.CharField(choices=[('Dentro de terminal', 'Dentro de terminal'), ('Fuera de terminal', 'Fuera de terminal')], default='Dentro de terminal', max_length=20),
        ),
    ]
