# Generated by Django 5.1.2 on 2024-10-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_empleado_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
