# Generated by Django 5.1.2 on 2024-10-17 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_encomienda_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='empleado_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado_entrega', to='sistema.empleado'),
        ),
    ]
