# Generated by Django 5.1.2 on 2024-11-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_encomienda_empleado_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
    ]
