# Generated by Django 5.1.2 on 2024-11-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_reclamo_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
