# Generated by Django 5.1.2 on 2024-11-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_alter_comprobante_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguridad',
            name='estado_habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
